# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Technology.create(name: "C")
Technology.create(name: "c++")
Technology.create(name: "Core Java")
Technology.create(name: "Advanced Java")
Technology.create(name: "Spring")
Technology.create(name: "Hibernate")
Technology.create(name: "Struts")
Technology.create(name: "XML")
Technology.create(name: "HTML")
Technology.create(name: "CSS")
Technology.create(name: "HTML5")
Technology.create(name: "CSS3")
Technology.create(name: "Saas")
Technology.create(name: "Ruby")
Technology.create(name: "Ruby On Rails ")
Technology.create(name: "Python")
Technology.create(name: "Django")
Technology.create(name: "Perl")
Technology.create(name: "Selenium")
Technology.create(name: "Hive")
Technology.create(name: "Pig")
Technology.create(name: "Hadoop")
Technology.create(name: "Android")
Technology.create(name: "IOS")
Technology.create(name: "Linux")
Technology.create(name: "Unix")
Technology.create(name: "MATLAB")
Technology.create(name: "JavaScript")
Technology.create(name: "JQuery")
Technology.create(name: "NodeJS")
Technology.create(name: "AngularJS")
Technology.create(name: "EmberJS")
Technology.create(name: "JQuery UI")
Technology.create(name: "Embedded Systems")
Technology.create(name: "Robotics")
Technology.create(name: "C#")
Technology.create(name: "Swift")
Technology.create(name: "Objective-C")
Technology.create(name: "Bootstrap")
Technology.create(name: "VBScript")
Technology.create(name: "Cassandra")
Technology.create(name: "VB.Net")
Technology.create(name: "SQL")
Technology.create(name: "MySQL")
Technology.create(name: "Oracle")
Technology.create(name: "PL/SQL")
Technology.create(name: "PostgreSQL")
Technology.create(name: "PhoneGap")
Technology.create(name: "HTTP")
Technology.create(name: "SOAP")
puts "seeding completed"